# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-26 19:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name_first', models.CharField(max_length=50)),
                ('name_last', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'player',
                'verbose_name_plural': 'players',
            },
        ),
        migrations.CreateModel(
            name='Attendee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('IN', 'Interested'), ('AP', 'Approved'), ('CO', 'Confirmed')], max_length=100, verbose_name='Status')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(default=django.utils.timezone.now, verbose_name='Time')),
                ('start_date', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('capacity', models.IntegerField(default=0, verbose_name='Capacity')),
                ('num_confirmed', models.IntegerField(default=0, verbose_name='Number Confirmed')),
                ('location', models.CharField(max_length=200)),
                ('notes', models.CharField(blank=True, max_length=200, verbose_name='Notes')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='attendee',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Event'),
        ),
        migrations.AddField(
            model_name='attendee',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='player',
            name='events',
            field=models.ManyToManyField(through='web.Attendee', to='web.Event'),
        ),
        migrations.AddField(
            model_name='player',
            name='friends',
            field=models.ManyToManyField(related_name='_player_friends_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
